### ISSUE TITLE
Android Chrome: Failed to construct 'Notification'.

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/arc#105]
> Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead. TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.

Because of [this](https://bugs.chromium.org/p/chromium/issues/detail?id=481856).

**Comment by Maiux92** [comment]
Hi, i'm sorry for bothering you. It seems that this bug is still present on my device and I'm using the latest version of chrome from playstore.
I don't know if it is the "cleantest" way to fix this, but in arc/js/notify.js I replaced the create_notification method's body with
`try {
    return new Notification(options.title, options);
} catch(e) {
    return null;
}`
Desktop notifications seems to work properly and on my phone it still asks for notifications permission (i'm not receiving them on my phone with the page open, though)

![photo_2018-01-10_02-48-58](https://user-images.githubusercontent.com/1405655/34752149-da56270e-f5b0-11e7-8708-34ab432e73c5.jpg)
