### ISSUE TITLE
Well, it's time to see some alternative to this software, after three years without any commit or merges

### ISSUE THREAD

**Issue by q2dg** [evilsocket/arc#154]
Sadly :-(

**Comment by wpa-2** [comment]
> Sadly :-(

What else would you like to see?

**Comment by q2dg** [comment]
Well, it's just about care. For instance, issue #153 mentions _go get_ command shown in README should be changed to _go install_ command because the former whas deprecated in Go 1.17. That was two years ago. Not having done a simple change like this in all this time is a signal that this project is not being maintained

**Comment by wpa-2** [comment]
Non of the projects are being maintained that's been known for a long time. 
Sadly he went on to other things.

**Comment by wpa-2** [comment]
> Sadly :-(

Did you ever find anything as good?

**Comment by q2dg** [comment]
Well, a combination of tools, 
Age: https://github.com/FiloSottile/age and Minisign: https://github.com/jedisct1/minisign or
Kryptor: https://github.com/samuel-lucas6/Kryptor
They haven't any REST API nor any way to get remote access but I use SSH to do that

**Comment by wpa-2** [comment]
@evilsocket Surely this is worthy of an update! 
happy new year by the way.

**Comment by evilsocket** [comment]
Misuse of github issues. 

I use this software since years on a daily basis and while its codebase didn't change much, to this day it is the most useful and functional software of its kind to me. I am not sure what's the deal with you guys other than pointing out minor changes in the README. If you have actual ideas about new features / fixes you can open an issue about it (instead of opening one to complain about ... what?). Most importantly, if I find those features interesting enough to be worth my time, i'll work on them, otherwise i won't, this is not a paid product after all. You are also welcome to work actively at the project and submit PRs with whatever code you want to add.

Peace.
